### ISSUE TITLE
when using right mouse button as scroller the ff menu shows up on release

### ISSUE THREAD

**Issue by ScottTu** [fastaddons/ScrollAnywhere#11]
this just started after yesterdays 75 update.  most annoyingly doing it on feedly.com

![image](https://user-images.githubusercontent.com/28675862/78820994-bbc4f280-79a6-11ea-9b91-d15d1bcea035.png)

**Comment by Juraj-Masiar** [comment]
Hello,
Thanks for reporting! This is really bad, it's a pity nobody noticed this during the beta :(.

I will investigate this further tomorrow, but from what I can see now, it occurs randomly, looks like race condition. Also it **seems to be happening only on pages with some "iframe" elements** (which is very common).

The good news is, **there is workaround** (with a tradeoff), open **Options page / Advanced / "Don't lock iframes and don't change cursor when scrolling" - enabling this option will fix the issue**, but scrolling over iframes won't work.

I will investigate and report to Firefox.

**Comment by Juraj-Masiar** [comment]
Thanks for the feedly.com, it's much easier to reproduce it there.

So after further investigation (I couldn't go to sleep without figuring this out :)), I found the problem and I can fix it in my extension, so no need to wait for Firefox team to fix it.

I will try to make a release tomorrow, but since Scroll Anywhere is now Recommended extension, it will have to be reviewed by Firefox team which will delay the release (hopefully not much).

Thanks again for reporting!

**Comment by ScottTu** [comment]
woohoo! :)

**Comment by DarKcyde0** [comment]
This has been driving me nuts all day.  Thanks for the quick fix!

**Comment by fastaddons** [comment]
Fixed version 8.3 is on the way, waiting for Firefox review (Queue Position: 6 of 6 ). All recommended extension are manually reviewed so this can take several hours / days.
