### ISSUE TITLE
Unclear License

### ISSUE THREAD

**Issue by geekley** [fastaddons/ScrollAnywhere#30]
What's the license for the extension? I can't find this info anywhere. Mozilla Addons only says "custom license" but there's no information in there, or here, or in the website. I even looked at the files inside the extension, but I didn't even find a copyright notice. I just found a README.md with typescript build instructions, it seems, but original source is not available...? This is confusing!

Is it proprietary? Is the source available anywhere? Or not? Are people allowed to modify or redistribute it?
How can I know what the extension does if I can't see the source? Or if I can't, **at least let me know** I can't.

If you just haven't chosen a license yet, you can use the Insights tab here on GitHub, then Community, then License to decide on one (if you want it open-source). It has really good info on what the typical options are, and what they mean.
If you don't want it open-source, you should at least add a copyright notice.

I suggest you add the LICENSE information and copyright notices:
- as a LICENSE text file in this repo and in the extension files
- in the store pages in relevant area (maybe even in the details section which shows up in the extension page on Firefox too)
- in the About section of the extension (with link to source, if you decide to publish it)

To be clear, again, I'm NOT asking you to make it open-source. You can keep it proprietary if you want, but please let people know what you decide. However, it does make sense to open-source it, since it's free and people can just look at the minified JS files anyway. And if you open-source it, they can contribute code as well!

**Comment by fastaddons** [comment]
Hello,
Thanks for pointing this out.
The Mozilla page should actually show "All Rights Reserved" (that's what I set in the settings), I'm not sure why it shows "Custom license". They were making some changes there, probably it's broken.

Anyway, it is indeed proprietary even though it's free. This Github repo doesn't have a license because there is no source code.
**But you are right, it's not clear and I will make a note in the readme and the addon description.**

I'm aware of benefits of open source software, however it's not that simple. I'm not a hobby programmer, I work on my addons full time for several years now and I would like to continue doing so. So eventually I'm trying to make some money out of it. I know it's possible with open source as well, but it's easier with closed source.
My addons are free now, but soon I will release Safari versions which for sure won't be free (I had to buy a Mac which was not cheap, plus 100$ per year as Apple developer...).

I don't know if you know, but addon developers doesn't make much money :). Look at my Patreon page and if you add about 50€ from one-time donations and you will get my total monthly salary! Crazy, right?

I was planning to try making some of my addons open source, but I'm so crazy busy all the time...

**Comment by geekley** [comment]
Thanks for the quick reply! That's good to know!

Hmm...
Since you said you work on this full-time ... if you allow a suggestion (just in case you haven't considered the possibility), some developers, like in [SmoothScroll](http://www.smoothscroll.net/) extension, offer paid desktop/native "premium" versions of their free browser extensions.

I don't know if that model works well in terms of profit, or if that makes sense for your extensions.
But I have to assume it's at least more profitable than just donations (and I think there's data evidence for that), because the free version works as an ad for the premium version (without people seeing it as an ad). And people are usually OK with free/premium features split if the split makes sense (and feels fair). Also, a native version can be compiled without easy access to source, unlike JS, so you could still make the free version open-source and focus mostly on features for the premium version.

Of course, it adds complexity, development costs, etc., but I just thought I'd mention it in case you haven't considered this possibility, because I've seen others do it.

**Comment by fastaddons** [comment]
Thank you for the ideas!
I'm not sure about desktop version though :). I can code well only in JavaScript / TypeScript and these are not ideal for desktop apps (they take a lot of RAM since they are wrapped in a hidden browser).

But I'm indeed planning to add "premium" features to some of my addons.
However to do that you need a server that can handle the verification of payed user plus integration with some money transfer services. So it's not that easy at all.
I'm now building a new server (for a few weeks already) for this exact reason, plus it will allow me to add new features more easily since my old server is build in Scala language :D (what was I thinking...).

Anyway, if I find a sponsor or somehow get rich one day, I will make it all open source. But my current goal is to survive since I'm running out of savings.

**Comment by fastaddons** [comment]
I've added license and privacy policy files.
https://github.com/fastaddons/ScrollAnywhere/blob/master/LICENSE
https://github.com/fastaddons/ScrollAnywhere/blob/master/PRIVACY_POLICY.md
