### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by wvxwxvw** [fastaddons/ScrollAnywhere#49]
So where are the translation files? Are you making it harder to find them on purpose?
There are addon pages on github, why not add translation files here so that we can send them to you via "Pull requests".

**Comment by fastaddons** [comment]
Hello,
Yeah, the situation is a bit more complicated :). First issue, was my own custom format for translations, since addons are using JSON which OK from the coding point of view but updating JSON manually is painful. But as I've learned, using custom format is pretty complex as well.

Anyway, I've [added translations ](https://github.com/fastaddons/ScrollAnywhere/commit/cffbe49370e5b60b6f2a075e1cf0a5f62ca1f816)in 2020 into some of my public repositories but it received no pull requests. As I've learned, github is too complicated for ordinary people who just want to help with translations.

So instead after I've upgraded my existing translation page I've build for my Group Speed Dial addon, I've made it able to translate all of my addons. So now users can translate my addons from that page:
https://translate.group-speed-dial.fastaddons.com/

If you would like to help with translation, just send me email with the language you want to translate and I will send you credentials for the page.

Alternatively, since I have all the messages from all addons in a single folder, maybe I can publish it into new github repository.... hmm, that way people would be able to use both ways. I can do that!

**Comment by wvxwxvw** [comment]
Hello,
JSON is easily formatted, then a comparison program is used, it is possible even without string alignment (this is even more convenient - the first difference is immediately visible, then the second, etc.). Then you can minimize JSON again.  
  
If I start using something and there is a bad translation, I just take it and translate. I can translate even if I don't use it, if translated a little. And this happens quite often. I have been translating for a long time, and I used to write something to the authors, I sent translations by mail, but life has taught me that it is not worth doing this, in most cases it is a stupid waste of time (I don't mean you). Another reason is that, after sending, the translation gets into the program only in a new version, in which there may be a lot of changes, and in the end we again get an untranslated program or in general - the parameter values have changed and the translation does not correspond to reality. For example, in this case, I already have the addon translated normally (so by and large I don't care), and since the author didn't bother with simple feedback, it means he doesn't need it.  
  
I am applying a normal Russian translation. And consider what I said above.
  
[messages.zip](https://github.com/fastaddons/ScrollAnywhere/files/8568345/messages.zip)

**Comment by fastaddons** [comment]
Thank you for the updated translations! I've updated it now so it will be part of the next release (probably upcoming week).
I've also created a new repository with all of my translations:
https://github.com/fastaddons/locales

I can imagine not many developers are eager to add or update translations, it takes time and it's super boring. Not to mention it's easy to forget it because it doesn't "break" anything even if it's out of date.
I wish whole world could speak one common language, that would save devs so much time and effort :)

Anyway, thanks again for your help!
