### ISSUE TITLE
Create a VS Code Extension (?)

### ISSUE THREAD

**Issue by MotaOcimar** [fastaddons/ScrollAnywhere#67]
I really liked this extension! I use a Pen Tablet to navigate through my computer and it makes this much more natural.
I don't use the native solution, Windows Ink, because its compatibility seems low with several use cases. For me, mainly VS Code, which I can't control at all with Windows Ink.

I was wondering... Since this Chrome extension has been extremely useful to me while browsing, would it be a possibility to make a similar extension for VS Code?

Oh, and thank you very much for developing it!

**Comment by MotaOcimar** [comment]
Or maybe help to create a new Windows feature? 
https://github.com/microsoft/PowerToys/issues/20087

**Comment by Juraj-Masiar** [comment]
Hello,
I'm sorry I didn't replied sooner. I've started investigating extensions development in VS Code but I've got stuck and then I forgot about it completely :).

The issue is, that extensions doesn't get access to the DOM:
https://code.visualstudio.com/api/extension-capabilities/overview#no-dom-access

And that's an issue since my extension needs to register several handlers in the DOM and also perform the scrolling and get current scroll position. There may be some workaround, but I don't know how. From what I can see it's not possible.
And sadly, my free time is now very limited and I have almost no time for my smaller extensions like this one :(.

**Comment by MotaOcimar** [comment]
Okay. I understand. Thank you for getting back to me anyway. Since it doesn't seem possible to make the extension for VS Code, I'll close this issue, okay?

Thanks again for your care with this extension. I'm still using it daily.

Best, 
Ocimar
