### ISSUE TITLE
Revert to original scrolling point via hotkey

### ISSUE THREAD

**Issue by samwolfe2000** [fastaddons/ScrollAnywhere#9]
linked to this add-on review: https://addons.mozilla.org/hu/firefox/addon/scroll_anywhere/reviews/1496458/

You are right regarding my first point, I just accidentaly disabled autoscroll in the browser options.

Yeah, you've got my second point as well, a keyboard or mouse hotkey to reset were you started on the page while scrolling.

the _Outside of range_ term related to my example with classic scrollbars, already having this function:

when almost any scrollbar is dragged, there's a maximum distance the cursor can be apart from the scrollbar, which when exceeded, the bar jumps back to it's original position and no longer senses mouse movement. If the cursor is dragged back _inside of range_, the bar jumps back to your cursor and can be controlled again. 

This means you can jump on the page back and forth with perpendicular mouse movement. 

I was thinking to translate this function to a hotkey solution in case of ScrollAnywhere.

there could be two modes: 
 - one which I described above, where you can jump on the page back and fouth;
 - one which permanently jumps back and senses your mouse movement continuously.

Thanks for your efforts, I really appreciate it.

Regards,
Sámuel Farkas

**Comment by fastaddons** [comment]
So what I should be able to do regarding **reset scroll position** is:
- **when key defined in Options page to disable scrolling is pressed** during the scrolling, I will revert position
- **when ESC key is pressed**, revert as well

Regarding **Outside of range** - so basically when you start scrolling (let's say Y axis), I will **define invisible rectangle with infinite height but limited width and centered to your mouse**, and once you leave it, it will revert the position. In Firefox the rectangle around scrollbar has only about 50px to each side (100px total). I will make it editable in Options page.

I will try to include these in the next release 8.3.
However I'm really busy right now with my other addon (GSD) so I'm not sure when I'll get to this. 
Also due to corona pandemic, my office is closed and my productivity at home is quite limited :(

**Comment by samwolfe2000** [comment]
I'm not sure if this **range stuff** is compatible with ScrollAnywhere, since it **works only on one axis**, while the add-on always uses two if possible.

A possibility, In case the page has two scrollable axis, is to use **axis constraints**, a function to lock down one of the axis depending on wich direction the cursor starts to move after triggering the scroll function.

This is a feature I often miss btw, because **badly designed pages often have unnecessary horizontal scrolling space** making the scroll waggling.

These two functions (axis canstraints and jump rectangle) could be packaged together, and be set for a hotkey to alter with normal mode.

Btw how can you make a living from creating free web extensions? I don't think you get so much coffee.

**Comment by fastaddons** [comment]
Good point. But usually there is only one axis so in most cases it should work fine.

The axis lock-down during scrolling is partially implemented, but it's not a full lock. 
This sounds more like a new feature: https://github.com/fastaddons/ScrollAnywhere/issues/10
Some users already requested that... I will have to make it compatible with that.

Regarding my living from creating webextension - well if you are thinking about becoming a full time extension developer, better think again :D. I do it because I love it, not because it's a good idea for making money. I have some savings from previous jobs, plus my expenses are low, so that's how :). 
But I'm trying to make some money by adding PRO features in my main extension GroupSpeedDial available to Patreon supporters only. Hopefully that will grow into something bigger.

However my savings are now very thin, so there is a chance I will soon work with a friend on some commercial project for a several months so these hobby projects of mine may get on hold soon.

**Comment by fastaddons** [comment]
Done, you will be able to stop and revert scrolling with ESC key AND you can define scrolling area in Options page / Advanced / Scrolling area. This has the same behavior as when dragging a scrollbar - moving too much to the side will revert position, moving back will jump back.

It will be part of 8.4 release any day now... just one more feature, tests and then review process...
